name:                GBTW
version:             0.1.0.0
github:              "Vojiranto/GTS"
license:             BSD3
author:              "Dmitriy Pavlyuk"
maintainer:          "example@example.com"
copyright:           "2018 Dmitriy Pavlyuk"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/Vojiranto/GTS#readme>

dependencies:
- base >= 4.7 && < 5
- haskell-neo4j-client
- unordered-containers
- bytestring
- text
- aeson
- scientific
- vector

library:
  source-dirs: src

executables:
  Task-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - haskell-neo4j-client
    - unordered-containers
    - bytestring
    - text
    - aeson
    - scientific
    - vector
    - GBTW

tests:
  Task-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - GBTW
